In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler, RobustScaler

# Data
data = np.array([150, 160, 165, 170, 300]).reshape(-1, 1)

In [2]:
# Min-Max Normalization
min_max_scaler = MinMaxScaler()
min_max_normalized = min_max_scaler.fit_transform(data)

print("Original Data:\n", data.flatten())
print("\nMin-Max Normalization:\n", min_max_normalized.flatten())


Original Data:
 [150 160 165 170 300]

Min-Max Normalization:
 [0.         0.06666667 0.1        0.13333333 1.        ]


In [3]:
# Mean Normalization (manual calculation)
mean = np.mean(data)
range_val = np.max(data) - np.min(data)
mean_normalized = (data - mean) / range_val

print("\nMean Normalization:\n", mean_normalized.flatten())


Mean Normalization:
 [-0.26       -0.19333333 -0.16       -0.12666667  0.74      ]


In [7]:
# Max Absolute Scaling
max_abs_scaler = MaxAbsScaler()
max_abs_normalized = max_abs_scaler.fit_transform(data)

print("\nMax Absolute Scaling:\n", max_abs_normalized.flatten())


Max Absolute Scaling:
 [0.5        0.53333333 0.55       0.56666667 1.        ]


In [8]:
# Robust Scaling
robust_scaler = RobustScaler()
robust_normalized = robust_scaler.fit_transform(data)

print("\nRobust Scaling:\n", robust_normalized.flatten())


Robust Scaling:
 [-1.5 -0.5  0.   0.5 13.5]


In [11]:
# Z-Score Normalization
z_score_scaler = StandardScaler()
z_score_normalized = z_score_scaler.fit_transform(data)

print("\nZ-Score Normalization:\n", z_score_normalized.flatten())


Z-Score Normalization:
 [-0.69776486 -0.51885079 -0.42939376 -0.33993673  1.98594614]
